// This file is automatically generated by ast_parser.py
// Please ensure you have run 'npm install esprima' in your project directory.

const esprima = require('esprima');
const fs = require('fs');

const inputFile = process.argv[2]; // 输入 JS 文件路径
const outputFile = process.argv[3]; // 输出 AST JSON 文件路径

try {
    const jsCode = fs.readFileSync(inputFile, 'utf8');
    // 解析选项：包括位置信息和范围信息，容忍一些错误
    const ast = esprima.parseScript(jsCode, { range: true, loc: true, tolerant: true });
    fs.writeFileSync(outputFile, JSON.stringify(ast, null, 2)); // 输出格式化的 JSON
    // console.log(`AST successfully generated for ${inputFile}`); // 用于调试
    process.exit(0); // 成功退出
} catch (e) {
    console.error(`Error parsing ${inputFile}:`, e.message);
    // 尝试输出错误信息到文件，以便 Python 捕获
    fs.writeFileSync(outputFile, JSON.stringify({ error: e.message, stack: e.stack }));
    process.exit(1); // 失败退出
}
